run:
  deadline: 5m

linters-settings:
  funlen:
    lines: 80
    statements: 100
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complecity: 10

linters:
  enable-all: true
  disable:
    - gosec
    - prealloc
    - dupl
    - godot
