before:
  hooks:
    - hack/update-version-gorelease.sh
    - go mod download

builds:
  - main: ./cmd/dfget
    id: dfget
    binary: dfget
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X d7y.io/dragonfly/v2/version.Major={{ .Major }}
      - -X d7y.io/dragonfly/v2/version.Minor={{ .Minor }}
      - -X d7y.io/dragonfly/v2/version.GitVersion={{ .Tag }}
      - -X d7y.io/dragonfly/v2/version.GitCommit={{ .ShortCommit }}
      - -X d7y.io/dragonfly/v2/version.BuildTime={{ .Date }}
      - -X "d7y.io/dragonfly/v2/version.Gotags=none"
      - -X "d7y.io/dragonfly/v2/version.Gogcflags=none"

  - main: ./cmd/scheduler
    id: scheduler
    binary: scheduler
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X d7y.io/dragonfly/v2/version.Major={{ .Major }}
      - -X d7y.io/dragonfly/v2/version.Minor={{ .Minor }}
      - -X d7y.io/dragonfly/v2/version.GitVersion={{ .Tag }}
      - -X d7y.io/dragonfly/v2/version.GitCommit={{ .ShortCommit }}
      - -X d7y.io/dragonfly/v2/version.BuildTime={{ .Date }}
      - -X "d7y.io/dragonfly/v2/version.Gotags=none"
      - -X "d7y.io/dragonfly/v2/version.Gogcflags=none"

  - main: ./cmd/cdn
    id: cdn
    binary: cdn
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X d7y.io/dragonfly/v2/version.Major={{ .Major }}
      - -X d7y.io/dragonfly/v2/version.Minor={{ .Minor }}
      - -X d7y.io/dragonfly/v2/version.GitVersion={{ .Tag }}
      - -X d7y.io/dragonfly/v2/version.GitCommit={{ .ShortCommit }}
      - -X d7y.io/dragonfly/v2/version.BuildTime={{ .Date }}
      - -X "d7y.io/dragonfly/v2/version.Gotags=none"
      - -X "d7y.io/dragonfly/v2/version.Gogcflags=none"

  - main: ./cmd/manager
    id: manager
    binary: manager
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X d7y.io/dragonfly/v2/version.Major={{ .Major }}
      - -X d7y.io/dragonfly/v2/version.Minor={{ .Minor }}
      - -X d7y.io/dragonfly/v2/version.GitVersion={{ .Tag }}
      - -X d7y.io/dragonfly/v2/version.GitCommit={{ .ShortCommit }}
      - -X d7y.io/dragonfly/v2/version.BuildTime={{ .Date }}
      - -X "d7y.io/dragonfly/v2/version.Gotags=none"
      - -X "d7y.io/dragonfly/v2/version.Gogcflags=none"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: dfget
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    package_name: dfget
    description: dfget is the client of Dragonfly used to download and upload files
    license: "Apache 2.0"
    homepage: https://d7y.io
    bindir: /usr/bin
    builds:
      - dfget
    formats:
      - rpm
      - deb
    contents:
      - src: build/package/nfpm/config/dfget.yaml
        dst: /etc/dragonfly/dfget.yaml
        type: config

      - src: build/package/docs/dfget.1
        dst: /usr/share/man/man1/dfget.1

      - src: LICENSE
        dst: /usr/share/doc/dfget/License

      - src: CHANGELOG.md
        dst: /usr/share/doc/dfget/ChangeLog

      - src: build/package/nfpm/systemd/dfget-daemon.service
        dst: /etc/systemd/system/dfget-daemon.service

      - src: build/package/nfpm/systemd/dfget-daemon.service.d/CPUQuota.conf
        dst: /etc/systemd/system/dfget-daemon.service.d/CPUQuota.conf

      - src: build/package/nfpm/systemd/dfget-daemon.service.d/CPUShares.conf
        dst: /etc/systemd/system/dfget-daemon.service.d/CPUShares.conf

      - src: build/package/nfpm/systemd/dfget-daemon.service.d/MemoryLimit.conf
        dst: /etc/systemd/system/dfget-daemon.service.d/MemoryLimit.conf

      - src: build/package/nfpm/systemd/fix.dfget-daemon.cpuset.sh
        dst: /opt/dragonfly/fix.dfget-daemon.cpuset.sh
    scripts:
      postinstall: build/package/nfpm/dfget-postinstall.sh
      preremove: build/package/nfpm/dfget-preremove.sh
      postremove: build/package/nfpm/dfget-postremove.sh
