# This file is the template of supernode configuration file.
# You can configure your supernode by change the parameter according your requirement.
---
base:
  # listenRpcPort is the port cdn rpc server listens on.
  # default: 8003
  listenRpcPort: 8003

  # listenHttpPort is the port cdn http server listens on.
  # default: 8002
  listenHttpPort: 8002

  # DownloadPort is the port for download files from cdn.
  # And you should start a file server firstly which listens on the download port.
  # default: 8001
  downloadPort: 8001

  # HomeDir is working directory of cdn.
  # default: /home/admin/cdn
  homeDir: /home/admin/cdn

  # the core pool size of ScheduledExecutorService.
  # When a request to start a download task, supernode will construct a thread concurrent pool
  # to download pieces of source file and write to specified storage.
  # Note: source file downloading is into pieces via range attribute set in HTTP header.
  # default: 10
  schedulerCorePoolSize: 10

  # SystemReservedBandwidth is the network bandwidth reserved for system software.
  # default: 20 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  systemReservedBandwidth: 20M

  # MaxBandwidth is the network bandwidth that cdn can use.
  # default: 200 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  maxBandwidth: 200M

  # Whether to enable profiler
  # default: false
  enableProfiler: false

  # Whether to open DEBUG level
  # default: false
  debug: false

  # FailAccessInterval is the interval time after failed to access the URL.
  # If a task failed to be downloaded from the source, it will not be retried in the time since the last failure.
  # default: 3m
  failAccessInterval: 3m

  # gc related

  # GCInitialDelay is the delay time from the start to the first GC execution.
  # default: 6s
  gcInitialDelay: 6s

  # GCMetaInterval is the interval time to execute GC meta.
  # default: 2m0s
  gcMetaInterval: 2m

  # TaskExpireTime when a task is not accessed within the taskExpireTime,
  # and it will be treated to be expired.
  # default: 3m0s
  taskExpireTime: 3m

  # PeerGCDelay is the delay time to execute the GC after the peer has reported the offline.
  # default: 3m0s
  peerGCDelay: 3m

  # GCDiskInterval is the interval time to execute GC disk.
  # default: 15s
  gcDiskInterval: 15s

  # YoungGCThreshold if the available disk space is more than YoungGCThreshold
  # and there is no need to GC disk.
  # default: 100GB
  youngGCThreshold: 100G

  #  FullGCThreshold if the available disk space is less than FullGCThreshold
  #  and the supernode should gc all task files which are not being used.
  #  default: 5GB
  fullGCThreshold: 5G

  # IntervalThreshold is the threshold of the interval at which the task file is accessed.
  # default: 2h0m0s
  IntervalThreshold: 2h

---
plugins:
  store:
    local:
      name: local
      enable: true
      config: fdas
  source:
    http:
      name: ddd
      enable: true
      config: fds
