{{- if .Values.scheduler.config.staticCDN }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{template "dragonfly.cdn.fullname" . }}-role
  namespace: {{ .Values.installation.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - patch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{template "dragonfly.cdn.fullname" . }}-role-binding
  namespace: {{ .Values.installation.namespace }}
roleRef:
  kind: Role
  name: {{template "dragonfly.cdn.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{template "dragonfly.cdn.fullname" . }}
{{ end }}