# 这个文件是 CDN 系统的配置模版
# 你可以通过修改这里的配置项来自定义你的 CDN 系统
---
base:  # 基础配置项
  # listenPort cdn 服务的监听端口.
  # default: 8003
  listenPort: 8003

  # DownloadPort CDN提供文件下载的端口.
  # 你需要先启动一个文件服务器，并且该文件服务器监听该下载端口。.
  # default: 8001
  downloadPort: 8001

  # SystemReservedBandwidth is the network bandwidth reserved for system software.
  # default: 20 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  systemReservedBandwidth: 20M

  # MaxBandwidth is the network bandwidth that cdn can use.
  # default: 1G, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  maxBandwidth: 1G

  # FailAccessInterval is the interval time after failed to access the URL.
  # If a task failed to be downloaded from the source, it will not be retried in the time since the last failure.
  # default: 3m
  failAccessInterval: 3m

  # GCInitialDelay is the delay time from the start to the first GC execution.
  # default: 6s
  gcInitialDelay: 6s

  # GCMetaInterval is the interval time to execute GC meta.
  # default: 2m0s
  gcMetaInterval: 2m

  # gcStorageInterval is the interval time to execute GC storage.
  # default: 15s
  gcStorageInterval: 15s

  # TaskExpireTime when a task is not accessed within the taskExpireTime,
  # and it will be treated to be expired.
  # default: 3m0s
  taskExpireTime: 3m

  # StoragePattern is the pattern of storage policy, [disk/hybrid]
  storagePattern: disk

plugins: # 插件配置
  storage: # 存储插件配置
    - name: disk
      enable: true
      config:
        baseDir: /tmp/cdnsystem2
        gcConfig:
          youngGCThreshold: 100G
          fullGCThreshold: 5G
          cleanRatio: 1
          intervalThreshold: 2h
    - name: memory
      enable: true
      config:
        baseDir: /tmp/memory/dragonfly
        gcConfig:
          youngGCThreshold: 100G
          fullGCThreshold: 5G
          cleanRatio: 3
          intervalThreshold: 2h

# Console shows log on console
# default: false
console: false

# Whether to enable debug level logger and enable pprof
# default: false
verbose: false

# listen port for pprof, only valid when the verbose option is true
# default is random port
pprofPort: 0

# the service address that provides the configuration item
configServer: 127.0.0.1:8004