scheduler:
  name: scheduler
  replicas: 2
  image: dragonflyoss/scheduler
  tag: 0.1.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  priorityClassName: ""
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  deploymentAnnotations: {}
  service:
    type: ClusterIP
    annotations: {}

cdnsystem:
  name: cdnsystem
  replicas: 2
  image: dragonflyoss/cdnsystem
  tag: 0.1.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  priorityClassName: ""
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  deploymentAnnotations: {}
  nginx:
    name: nginx
    image: nginx
    tag: stable
    pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "512m"
        memory: "512Mi"
      limits:
        cpu: "512m"
        memory: "512Mi"
  service:
    type: ClusterIP
    annotations: {}

client:
  name: client
  image: dragonflyoss/client
  tag: 0.1.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  priorityClassName: ""
  nodeSelector: {}
  terminationGracePeriodSeconds:
  tolerations: []
  podAnnotations: {}
  deploymentAnnotations: {}
