scheduler:
  name: scheduler
  replicas: 2
  image: dragonflyoss/scheduler
  tag: 0.1.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  service:
    type: ClusterIP

cdnsystem:
  name: cdnsystem
  replicas: 2
  image: dragonflyoss/cdnsystem
  tag: 0.1.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  service:
    type: ClusterIP

client:
  name: client
  replicas: 2
  image: dragonflyoss/client
  tag: 0.1.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
