# This file is the template of scheduler configuration file.
# You can configure your scheduler by change the parameter according your requirement.
---
server:
  ip: ""
  # ListenPort is the ip and port supernode server listens on.
  # default: 8002
  port: 8002

scheduler:
  max-usable-value: 100.0
  max-upload-piece-num: 3
  max-download-piece-num: 3

worker:
  worker-num: 5
  worker-job-pool-size: 10000
  sender-num: 10
  sender-job-pool-size: 10000

cdn:
  list:
    -
      - ip: "127.0.0.1"
        port: 12345

