namespace: dragonfly-system
resources:
- ../../bases
images:
- name: dragonflyoss/cdn
  newTag: v0.1.0-beta
- name: dragonflyoss/dfdaemon
  newTag: v0.1.0-beta
- name: dragonflyoss/scheduler
  newTag: v0.1.0-beta
