apiVersion: v1
kind: Service
metadata:
  name: cdn
spec:
  selector:
    app: dragonfly
    component: cdn
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 8003
    protocol: TCP
    targetPort: 8003
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001