basePath: /api/v2
definitions:
  handler.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  types.ListSchedulerClustersResponse:
    properties:
      clusters:
        items:
          $ref: '#/definitions/types.SchedulerCluster'
        type: array
    type: object
  types.SchedulerCluster:
    properties:
      client_config:
        type: string
      cluster_id:
        type: string
      created_at:
        type: string
      creator:
        type: string
      modifier:
        type: string
      scheduler_config:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /schedulerclusters:
    get:
      consumes:
      - application/json
      description: List by object
      parameters:
      - description: begin marker of current page
        in: query
        name: marker
        required: true
        type: integer
      - description: return max item count, default 10, max 50
        in: query
        name: maxItemCount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.ListSchedulerClustersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.HTTPError'
      summary: List scheduler clusters
      tags:
      - SchedulerCluster
    post:
      consumes:
      - application/json
      description: add by json config
      parameters:
      - description: Scheduler cluster
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/types.SchedulerCluster'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SchedulerCluster'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.HTTPError'
      summary: Add scheduler cluster
      tags:
      - SchedulerCluster
  /schedulerclusters/{id}:
    delete:
      consumes:
      - application/json
      description: Delete by clusterId
      parameters:
      - description: ClusterId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.HTTPError'
      summary: Delete scheduler cluster
      tags:
      - SchedulerCluster
    get:
      consumes:
      - application/json
      description: Get scheduler cluster by ClusterId
      parameters:
      - description: ClusterId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.SchedulerCluster'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.HTTPError'
      summary: Get scheduler cluster
      tags:
      - SchedulerCluster
    post:
      consumes:
      - application/json
      description: Update by json scheduler cluster
      parameters:
      - description: ClusterId
        in: path
        name: id
        required: true
        type: string
      - description: SchedulerCluster
        in: body
        name: Cluster
        required: true
        schema:
          $ref: '#/definitions/types.SchedulerCluster'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.HTTPError'
      summary: Update scheduler cluster
      tags:
      - SchedulerCluster
swagger: "2.0"
