verbose: true

server:
  port: 8002

worker:
  workerNum: 4
  workerJobPoolSize: 10000
  senderNum: 10
  senderJobPoolSize: 10000

dynconfig:
  cdnDirPath: /opt/dragonfly/scheduler-cdn
manager:
  addr: manager.svc.cluster:65003
  schedulerClusterID: 1
  keepAlive:
    interval: 5s
job:
  redis:
    password: dragonfly
    host: redis-master.svc.cluster
    port: 6379