# This file is the template of cdn system configuration file.
# You can configure your cdn system by change the parameter according your requirement.
---
base:
  # listenPort is the port cdn server listens on.
  # default: 8003
  listenPort: 8003

  # DownloadPort is the port for download files from cdn.
  # And you should start a file server firstly which listens on the download port.
  # default: 8001
  downloadPort: 8001

  # SystemReservedBandwidth is the network bandwidth reserved for system software.
  # default: 20 MB, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  systemReservedBandwidth: 20M

  # MaxBandwidth is the network bandwidth that cdn can use.
  # default: 1G, in format of G(B)/g/M(B)/m/K(B)/k/B, pure number will also be parsed as Byte.
  maxBandwidth: 1G

  # CDN 暴露给 p2p 网络中的其他 peer 的 IP 地址
  # 默认值：首个非本地回环IP。
  advertiseIP:

  # CDN 请求某个 URL 失败后，不再对该 URL 发起请求的时间间隔长度
  # 换句话说，如果一个回源下载任务失败了，在这段时间里它将不会被重试。
  # 默认值：3m
  failAccessInterval: 3m

  # GCInitialDelay is the delay time from the start to the first GC execution.
  # default: 6s
  gcInitialDelay: 6s

  # GCMetaInterval is the interval time to execute GC meta.
  # default: 2m0s
  gcMetaInterval: 2m

  # TaskExpireTime when a task is not accessed within the taskExpireTime,
  # and it will be treated to be expired.
  # default: 3m0s
  taskExpireTime: 3m

  # storageMode is the Mode of storage policy, [disk/hybrid]
  storageMode: disk

  # manager configuration
  manager:
    addr: ""
    cdnClusterID: 0
    keepAlive:
      interval: 5s

  # host configuration
  host:
    location:
    idc:

plugins:
  storagedriver:
    - name: disk
      enable: true
      config:
        baseDir: /Users/Zhangzheyi/ftp
    - name: memory
      enable: false
      config:
        baseDir: /dev/shm/dragonfly
  storagemanager:
    - name: disk
      enable: true
      config:
        gcInitialDelay: 0s
        gcInterval: 15s
        driverConfigs:
          disk:
            gcConfig:
              youngGCThreshold: 100.0GB
              fullGCThreshold: 5.0GB
              cleanRatio: 1
              intervalThreshold: 2h0m0s
    - name: hybrid
      enable: false
      config:
        gcInitialDelay: 0s
        gcInterval: 15s
        driverConfigs:
          disk:
            gcConfig:
              youngGCThreshold: 100.0GB
              fullGCThreshold: 5.0GB
              cleanRatio: 1
              intervalThreshold: 2h0m0s
          memory:
            gcConfig:
              youngGCThreshold: 100.0GB
              fullGCThreshold: 5.0GB
              cleanRatio: 3
              intervalThreshold: 2h0m0s

# Console shows log on console
# default: false
console: false

# Whether to enable debug level logger and enable pprof
# default: false
verbose: false

# listen port for pprof, only valid when the verbose option is true
# default is -1. If it is 0, pprof will use a random port.
pprofPort: -1

# jaeger endpoint url
jaeger:

# service name used in tracer
# default: dragonfly-cdn
service-name: dragonfly-cdn
