# daemon alive time, when sets 0s, daemon will not auto exit
# it is useful for longtime running
alive_time: 0s

# daemon gc task running interval
gc_interval: 1m0s

# daemon data directory
# in linux, default value is $HOME/.dragonfly/dfget-daemon/
# in macos(just for testing), default value is /Users/$USER/.dragonfly/dfdaemon/
data_dir: /var/lib/dragonfly

# daemon work directory, daemon will change current working directory to this
# in linux, default value is $HOME/.dragonfly/dfget-daemon/
# in macos(just for testing), default value is /Users/$USER/.dragonfly/dfdaemon/
work_home: /var/lib/dragonfly

# when daemon exit, keep peer task data or not
# it is usefully when upgrade daemon service, all local cache will be saved
# default is false
keep_storage: true

# all addresses of all schedulers
# the schedulers of all daemons should be same in one region or zone.
# daemon will send tasks to a fixed scheduler by hashing the task url and meta data
# caution: only tcp is supported
scheduler:
  # schedule timeout
  schedule_timeout: 30s
  # below example is a stand address
  net_addrs:
    - type: tcp
      addr: 127.0.0.1:8002

# when enable, pprof will be enabled
verbose: true
# telemetry config
telemetry:
  # jaeger url, like: http://jaeger.dragonfly.svc:14268
  jaeger: ""

# current host info used for scheduler
host:
  # tcp service listen address
  # port should be set by other options
  listen_ip: 0.0.0.0
  # access ip for other peers
  # when local ip is different with access ip, advertise_ip should be set
  advertise_ip: 0.0.0.0
  # geographical location and network topology
  location: ""
  idc: ""
  security_domain: ""
  net_topology: ""

# download service option
download:
  # total download limit per second
  total_rate_limit: 200Mi
  # per peer task download limit per second
  per_peer_rate_limit: 100Mi
  # download grpc option
  download_grpc:
    # security option
    security:
      insecure: true
      cacert: ""
      cert: ""
      key: ""
      tls_config: null
    # download service listen address
    # current, only support unix domain socket
    unix_listen:
      # in linux, default value is /var/run/dfdaemon.sock
      # in macos(just for testing), default value is /tmp/dfdaemon.sock
      socket: /var/run/dfdaemon.sock
  # peer grpc option
  # peer grpc service send pieces info to other peers
  peer_grpc:
    security:
      insecure: true
      cacert: ""
      cert: ""
      key: ""
    tcp_listen:
      # listen address
      listen: 0.0.0.0
      # listen port, daemon will try to listen
      # when this port is not available, daemon will try next port
      port: 65000
      # if want to limit upper port, please use blow format
#     port:
#       start: 65000
#       end: 65009

# upload service option
upload:
  # upload limit per second
  rate_limit: 100Mi
  security:
    insecure: true
    cacert: ""
    cert: ""
    key: ""
  tcp_listen:
    # listen address
    listen: 0.0.0.0
    # listen port, daemon will try to listen
    # when this port is not available, daemon will try next port
    port: 65002
    # if want to limit upper port, please use blow format
#   port:
#     start: 65020
#     end: 65029

# peer task storage option
storage:
  # task data expire time
  # when there is no access to a task data, this task will be gc.
  task_expire_time: 3m0s
  # storage strategy when process task data
  # io.d7y.storage.v2.simple : download file to data directory first, then copy to output path, this is default action
  #                           the download file in date directory will be the peer data for uploading to other peers
  # io.d7y.storage.v2.advance: download file directly to output path with postfix, hard link to final output,
  #                            avoid copy to output path, fast than simple strategy, but:
  #                            the output file with postfix will be the peer data for uploading to other peers
  #                            when user delete or change this file, this peer data will be corrupted
  # default is io.d7y.storage.v2.advance
  strategy: io.d7y.storage.v2.advance
  # disk quota gc threshold, when the quota of all tasks exceeds the gc threshold, oldest tasks will be reclaimed.
  disk_gc_threshold: 50Gi

# proxy service config file location or detail config
# proxy: ""

# proxy service detail option
proxy:
  security:
    insecure: true
    cacert: ""
    cert: ""
    key: ""
  tcp_listen:
    # listen address
    listen: 0.0.0.0
    # listen port, daemon will try to listen
    # when this port is not available, daemon will try next port
    port: 65001
    # if want to limit upper port, please use blow format
  #   port:
  #     start: 65020
  #     end: 65029
  registry_mirror:
    # url for the registry mirror
    url: https://index.docker.io
    # whether to ignore https certificate errors
    insecure: true
    # optional certificates if the remote server uses self-signed certificates
    certs: []
    # whether to request the remote registry directly
    direct: false

  proxies:
    # proxy all http image layer download requests with dfget
    - regx: blobs/sha256.*
    # change http requests to some-registry to https and proxy them with dfget
    - regx: some-registry/
      use_https: true
    # proxy requests directly, without dfget
    - regx: no-proxy-reg
      direct: true
    # proxy requests with redirect
    - regx: some-registry
      redirect: another-registry

  hijack_https:
    # key pair used to hijack https requests
    cert: ""
    key: ""
    hosts:
      - regx: mirror.aliyuncs.com:443 # regexp to match request hosts
        # whether to ignore https certificate errors
        insecure: true
        # optional certificates if the host uses self-signed certificates
        certs: []

  white_list:
    # the host of the whitelist
    - host: ""
      # match whitelist hosts
      regx:
      # port that need to be added to the whitelist
      ports:
