# This file is the template of scheduler configuration file.
# You can configure your scheduler by change the parameter according your requirement.
---
debug: false

server:
  # ListenPort is the ip and port supernode server listens on.
  # default: 8002
  port: 8002

scheduler:

worker:
  worker-num: 1
  worker-job-pool-size: 10000
  sender-num: 10
  sender-job-pool-size: 10000

cdn:
  servers:
    - name: "B-M75UMD6M-2153.local"
      ip: "127.0.0.1"
      rpc-port: 8003
      download-port: 8001
