name: CI

on:
  push:
    branches:
      - main
      - feature/github
  pull_request:
    branches:
      - main
      - feature/github

jobs:

  lint:
    name: golangci-lint
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [ 1.15 ]
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  test:
    name: test
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [ 1.15 ]
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -v ./...
