name: Compatibility E2E Test

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

env:
  GO_VERSION: 1.15
  KIND_VERSION: v0.11.1
  CONTAINERD_VERSION: v1.5.2
  GOPROXY: https://goproxy.io,direct
  KIND_CONFIG_PATH: test/testdata/kind/config.yaml
  DRAGONFLY_E2E_TEST_MODE: compatibility
  DRAGONFLY_DFDAEMON_IMAGE_TAG: v0.4.0
  DRAGONFLY_CHARTS_PATH: deploy/helm-charts/charts/dragonfly
  DRAGONFLY_CHARTS_CONFIG_PATH: test/testdata/charts/config.yaml
  DRAGONFLY_FILE_SERVER_PATH: test/testdata/k8s/file-server.yaml

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Skip Check
        id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.png", "**.jpg", "**.svg"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  e2e_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["manager", "scheduler", "cdn", "dfdaemon"]
    needs: skip_check
    if: needs.skip_check.outputs.noop != 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go mod vendor
          go get github.com/onsi/ginkgo/ginkgo
          mkdir -p /tmp/artifact

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: ${{ env.KIND_VERSION }}
          config: ${{ env.KIND_CONFIG_PATH }}

      - name: Run compatibility E2E test
        env:
          MODULE: ${{ matrix.module }}
        run: |
          make docker-build
          make kind-load
          docker pull dragonflyoss/${{ env.MODULE }}:${{ env.DRAGONFLY_DFDAEMON_IMAGE_TAG }}
          kind load docker-image dragonflyoss${{ env.MODULE }}:${{ env.DRAGONFLY_DFDAEMON_IMAGE_TAG }}
          helm install --wait --timeout 10m --dependency-update --create-namespace --namespace dragonfly-system --set ${{ env.MODULE }}.tag=${{ env.DRAGONFLY_DFDAEMON_IMAGE_TAG }} -f ${{ env.DRAGONFLY_CHARTS_CONFIG_PATH }} dragonfly ${{ env.DRAGONFLY_CHARTS_PATH }}
          kubectl apply -f ${{ env.DRAGONFLY_FILE_SERVER_PATH }}
          kubectl wait po file-server-0 --namespace dragonfly-e2e --for=condition=ready --timeout=10m
          make actions-e2e-test

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: dragonfly-logs
          path: /tmp/artifact/
