name: License Check
on:
  pull_request:
    branches: [ main, release-* ]
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install license finder
        run: gem install license_finder

      - name: Run license finder
        run: license_finder
